let db=loadDb();
let currentView="dashboard";
const SHIFTS=["Manhã","Tarde","Noite"];

function $(id){return document.getElementById(id)}
function init(){document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));show("dashboard")}
function show(view){currentView=view;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(view).classList.add("active");document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));render()}
function render(){db=loadDb();if(currentView==="dashboard")renderDashboard();if(currentView==="production")renderProduction();if(currentView==="structure")renderStructure();if(currentView==="profiles")renderProfiles();if(currentView==="stats")renderStats();if(currentView==="data")renderData();if(currentView==="ai")renderAi()}

function kpis(records){const a=aggregate(records);return `<div class="grid"><div class="kpi">OF<b>${a.of}</b></div><div class="kpi">RNC<b>${a.rnc}</b></div><div class="kpi">Taxa RNC/100 OF<b>${fmt(a.taxa)}</b></div><div class="kpi">OF por RNC<b>${a.ofRnc?String(a.ofRnc.toFixed(1)).replace(".",","):"Sem RNC"}</b></div></div>`}
function bar(label,value,max,suffix=""){const w=max?Math.max(3,value/max*100):3;return `<div class="barline"><div class="barlabel">${label}</div><div class="barbox"><div class="bar" style="width:${w}%">${String(value.toFixed?value.toFixed(2):value).replace(".",",")}${suffix}</div></div></div>`}
function selectOptions(list,value="",empty=""){return (empty?`<option value="">${empty}</option>`:"")+list.map(x=>`<option value="${x.id}" ${x.id===value?"selected":""}>${x.name}</option>`).join("")}
function shiftOptions(value="",empty="Escolher"){return (empty?`<option value="">${empty}</option>`:"")+SHIFTS.map(s=>`<option value="${s}" ${s===value?"selected":""}>${s}</option>`).join("")}
function machineOptions(sectionId="",value=""){return selectOptions(db.machines.filter(m=>!sectionId||m.sectionId===sectionId),value,"Escolher")}
function workerChecks(selected=[]){return db.workers.map(w=>`<label><input type="checkbox" value="${w.id}" ${selected.includes(w.id)?"checked":""}> ${w.name} <span class="small">(${w.shift||"turno não definido"})</span></label>`).join("")||"<p class='small'>Sem trabalhadores criados.</p>"}
function recordShift(r){if(r.shift)return r.shift;const t=db.teams.find(x=>x.id===r.teamId);return t?.shift||"Não definido"}

function renderDashboard(){const thisYear=new Date().getFullYear();const month=new Date().getMonth();const monthRecords=recordsFor(db,{year:thisYear,month});const all=recordsFor(db,{});$("dashboard").innerHTML=`<div class="card"><h2>Dashboard</h2>${kpis(monthRecords)}<p class="small">Mês atual: ${MONTHS[month]} ${thisYear}</p></div><div class="row"><div class="card"><h2>Acumulado geral</h2>${kpis(all)}</div><div class="card"><h2>Alertas</h2>${alerts(all)}</div></div>`}
function alerts(records){const avg=aggregate(records).taxa||0;const byMachine=db.machines.map(m=>({m,agg:aggregate(records.filter(r=>r.machineId===m.id))})).filter(x=>x.agg.of>0).sort((a,b)=>(b.agg.taxa||0)-(a.agg.taxa||0));if(!byMachine.length)return"<p class='small'>Sem dados.</p>";return `<p>Pior máquina: <b>${byMachine[0].m.name}</b> (${fmt(byMachine[0].agg.taxa)}).</p><p>Média global: <b>${fmt(avg)}</b>.</p>`}

function renderProduction(){const year=new Date().getFullYear();$("production").innerHTML=`<div class="card"><h2>Produção mensal</h2><div class="grid"><div><label>Ano</label><input id="pYear" type="number" value="${year}"></div><div><label>Mês</label><select id="pMonth">${MONTHS.map((m,i)=>`<option value="${i}">${m}</option>`).join("")}</select></div><div><label>Secção</label><select id="pSection">${selectOptions(db.sections,"","Escolher")}</select></div><div><label>Máquina</label><select id="pMachine"></select></div><div><label>Equipa</label><select id="pTeam">${selectOptions(db.teams,"","Sem equipa")}</select></div><div><label>Turno</label><select id="pShift">${shiftOptions()}</select></div><div><label>OF/trabalhos</label><input id="pJobs" type="number" min="0"></div><div><label>RNC</label><input id="pRnc" type="number" min="0"></div><div><label>Causa principal</label><input id="pCause" placeholder="Ex: limpeza, setup, tinta"></div></div><label>Trabalhadores presentes</label><div id="pWorkers">${workerChecks([])}</div><label>Observações</label><textarea id="pNotes"></textarea><button class="btn" id="addRecord">Guardar registo</button></div><div class="card"><h2>Últimos registos</h2><div id="recordList"></div></div>`;$("pSection").onchange=()=>{$("pMachine").innerHTML=machineOptions($("pSection").value)};$("pTeam").onchange=()=>{const t=db.teams.find(x=>x.id===$("pTeam").value);if(t?.shift)$("pShift").value=t.shift};$("pSection").dispatchEvent(new Event("change"));$("addRecord").onclick=addRecord;renderRecordList()}
function addRecord(){const workerIds=[...document.querySelectorAll("#pWorkers input:checked")].map(x=>x.value);const rec={id:uid("rec"),year:n($("pYear").value),month:n($("pMonth").value),sectionId:$("pSection").value,machineId:$("pMachine").value,teamId:$("pTeam").value,shift:$("pShift").value,workerIds,jobs:n($("pJobs").value),rnc:n($("pRnc").value),cause:$("pCause").value.trim(),notes:$("pNotes").value.trim()};if(!rec.sectionId||!rec.machineId)return alert("Escolhe secção e máquina.");db.productionRecords.push(rec);saveDb(db);renderProduction()}
function renderRecordList(){const rows=[...db.productionRecords].slice(-12).reverse();$("recordList").innerHTML=rows.length?`<table><tr><th>Data</th><th>Secção</th><th>Máquina</th><th>Equipa</th><th>Turno</th><th>OF</th><th>RNC</th><th>Taxa</th></tr>${rows.map(r=>`<tr><td>${MONTHS[r.month]} ${r.year}</td><td>${sectionName(db,r.sectionId)}</td><td>${machineName(db,r.machineId)}</td><td>${teamName(db,r.teamId)}</td><td>${recordShift(r)}</td><td>${r.jobs}</td><td>${r.rnc}</td><td>${fmt(rate(r.rnc,r.jobs))}</td></tr>`).join("")}</table>`:"<p class='small'>Sem registos.</p>"}

function renderStructure(){$("structure").innerHTML=`<div class="row"><div class="card"><h2>Máquinas</h2><div class="grid"><input id="mName" placeholder="Ex: IF5"><select id="mSection">${selectOptions(db.sections)}</select><input id="mMaker" placeholder="Fabricante"><input id="mYear" placeholder="Ano"></div><button class="btn" id="addMachine">Adicionar máquina</button><div id="machineTable"></div></div><div class="card"><h2>Equipas</h2><input id="tName" placeholder="Nome da equipa"><select id="tSection">${selectOptions(db.sections)}</select><select id="tShift">${shiftOptions()}</select><button class="btn" id="addTeam">Adicionar equipa</button><div id="teamTable"></div></div></div><div class="card"><h2>Trabalhadores</h2><div class="grid"><input id="wName" placeholder="Nome"><input id="wNumber" placeholder="Nº mecanográfico"><input id="wNationality" placeholder="Nacionalidade"><input id="wBirth" type="date"><input id="wCompanyYears" type="number" placeholder="Anos na empresa"><input id="wPrintYears" type="number" placeholder="Anos na impressão"><select id="wTeam">${selectOptions(db.teams,"","Sem equipa")}</select><select id="wShift">${shiftOptions()}</select><input id="wRole" placeholder="Função"></div><label>Notas / formação / competências</label><textarea id="wNotes"></textarea><button class="btn" id="addWorker">Adicionar trabalhador</button><div id="workerTable"></div></div>`;$("addMachine").onclick=addMachine;$("addTeam").onclick=addTeam;$("addWorker").onclick=addWorker;renderStructureTables()}
function addMachine(){const name=$("mName").value.trim();if(!name)return;db.machines.push({id:name,name,sectionId:$("mSection").value,manufacturer:$("mMaker").value,year:$("mYear").value,notes:""});saveDb(db);renderStructure()}
function addTeam(){const name=$("tName").value.trim();if(!name)return;db.teams.push({id:uid("team"),name,sectionId:$("tSection").value,shift:$("tShift").value,members:[]});saveDb(db);renderStructure()}
function addWorker(){const name=$("wName").value.trim();if(!name)return;db.workers.push({id:uid("worker"),name,number:$("wNumber").value,nationality:$("wNationality").value,birthDate:$("wBirth").value,yearsCompany:n($("wCompanyYears").value),yearsPrinting:n($("wPrintYears").value),teamId:$("wTeam").value,shift:$("wShift").value,role:$("wRole").value,notes:$("wNotes").value});saveDb(db);renderStructure()}
function renderStructureTables(){ $("machineTable").innerHTML=`<table><tr><th>Máquina</th><th>Secção</th><th>Fabricante</th><th>Ano</th></tr>${db.machines.map(m=>`<tr><td>${m.name}</td><td>${sectionName(db,m.sectionId)}</td><td>${m.manufacturer||"—"}</td><td>${m.year||"—"}</td></tr>`).join("")}</table>`;$("teamTable").innerHTML=`<table><tr><th>Equipa</th><th>Secção</th><th>Turno</th></tr>${db.teams.map(t=>`<tr><td>${t.name}</td><td>${sectionName(db,t.sectionId)}</td><td>${t.shift||"—"}</td></tr>`).join("")}</table>`;$("workerTable").innerHTML=`<table><tr><th>Nome</th><th>Nacionalidade</th><th>Equipa</th><th>Turno</th><th>Exp. impressão</th></tr>${db.workers.map(w=>`<tr><td>${w.name}</td><td>${w.nationality||"—"}</td><td>${teamName(db,w.teamId)}</td><td>${w.shift||"—"}</td><td>${w.yearsPrinting||0}</td></tr>`).join("")}</table>`}

function renderProfiles(){const opts=`<option value="">Escolher</option>`;$("profiles").innerHTML=`<div class="card"><h2>Fichas</h2><div class="grid"><div><label>Secção</label><select id="fSection">${opts+db.sections.map(s=>`<option value="${s.id}">${s.name}</option>`).join("")}</select></div><div><label>Máquina</label><select id="fMachine">${opts+db.machines.map(m=>`<option value="${m.id}">${m.name}</option>`).join("")}</select></div><div><label>Equipa</label><select id="fTeam">${opts+db.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join("")}</select></div><div><label>Trabalhador</label><select id="fWorker">${opts+db.workers.map(w=>`<option value="${w.id}">${w.name}</option>`).join("")}</select></div></div></div><div id="profileOut"></div>`;["fSection","fMachine","fTeam","fWorker"].forEach(id=>$(id).onchange=renderProfileOut);renderProfileOut()}
function profile(title,sub,records,extra=""){return `<div class="card profile-card"><h2>${title}</h2><p class="small">${sub}</p>${kpis(records)}${extra}</div>`}
function renderProfileOut(){let html="";const s=$("fSection")?.value,m=$("fMachine")?.value,t=$("fTeam")?.value,w=$("fWorker")?.value;if(s)html+=profile("Ficha da secção — "+sectionName(db,s),"Dados agregados da secção.",recordsFor(db,{sectionId:s}));if(m){const machine=db.machines.find(x=>x.id===m);html+=profile("Ficha da máquina — "+machineName(db,m),`Secção: ${sectionName(db,machine.sectionId)}. Fabricante: ${machine.manufacturer||"—"}. Ano: ${machine.year||"—"}.`,recordsFor(db,{machineId:m}))}if(t){const team=db.teams.find(x=>x.id===t);html+=profile("Ficha da equipa — "+teamName(db,t),`Turno: ${team?.shift||"—"}. Dados associados à equipa.`,recordsFor(db,{teamId:t}))}if(w){const worker=db.workers.find(x=>x.id===w);const age=worker.birthDate?Math.floor((Date.now()-new Date(worker.birthDate))/(365.25*24*3600*1000)):"—";html+=profile("Ficha do trabalhador — "+worker.name,`Nº: ${worker.number||"—"}. Idade: ${age}. Nacionalidade: ${worker.nationality||"—"}. Equipa: ${teamName(db,worker.teamId)}. Turno: ${worker.shift||"—"}.`,recordsFor(db,{workerId:w}),`<p><b>Experiência:</b> ${worker.yearsCompany||0} anos na empresa, ${worker.yearsPrinting||0} anos na impressão.</p><p><b>Função:</b> ${worker.role||"—"}</p><p><b>Notas:</b> ${worker.notes||"—"}</p><p class="small">Dados de desempenho são associados aos registos onde o trabalhador esteve presente. Usar para análise estatística, não culpabilização.</p>`)}$("profileOut").innerHTML=html||"<div class='card'><p class='small'>Escolhe uma entidade para abrir a ficha.</p></div>"}

function renderStats(){const all=recordsFor(db,{});const byTeam=db.teams.map(t=>({name:t.name,a:aggregate(recordsFor(db,{teamId:t.id}))})).filter(x=>x.a.of>0);const max=Math.max(...byTeam.map(x=>x.a.of),1);$("stats").innerHTML=`<div class="card"><h2>Estatística</h2>${kpis(all)}</div><div class="card"><h2>Ranking de equipas por OF</h2>${byTeam.map(x=>bar(x.name,x.a.of,max)).join("")||"<p class='small'>Sem dados por equipa.</p>"}</div><div class="card"><h2>Influência por turno</h2>${shiftStats()}</div><div class="card"><h2>Estatísticas de trabalhadores</h2>${workerStats()}</div>`}
function shiftStats(){const rows=SHIFTS.concat(["Não definido"]).map(shift=>{const recs=db.productionRecords.filter(r=>recordShift(r)===shift);return{shift,a:aggregate(recs)}}).filter(x=>x.a.of>0);if(!rows.length)return"<p class='small'>Sem dados por turno.</p>";return `<table><tr><th>Turno</th><th>OF</th><th>RNC</th><th>Taxa</th><th>OF/RNC</th></tr>${rows.map(x=>`<tr><td>${x.shift}</td><td>${x.a.of}</td><td>${x.a.rnc}</td><td>${fmt(x.a.taxa)}</td><td>${x.a.ofRnc?x.a.ofRnc.toFixed(1).replace(".",","):"Sem RNC"}</td></tr>`).join("")}</table>`}
function workerStats(){if(!db.workers.length)return"<p class='small'>Sem trabalhadores.</p>";const avgExp=db.workers.reduce((a,w)=>a+n(w.yearsPrinting),0)/db.workers.length;const nat={};db.workers.forEach(w=>nat[w.nationality||"Não indicado"]=(nat[w.nationality||"Não indicado"]||0)+1);return `<p>Experiência média em impressão: <b>${avgExp.toFixed(1).replace(".",",")} anos</b></p><table><tr><th>Nacionalidade</th><th>Nº trabalhadores</th></tr>${Object.entries(nat).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join("")}</table>`}

function renderData(){$("data").innerHTML=`<div class="card"><h2>Dados</h2><button class="btn" id="exportBtn">Exportar JSON</button> <label class="import-label" for="importFile">Importar JSON</label><input id="importFile" type="file" accept="application/json,.json"><p class="small">O ficheiro guarda secções, máquinas, equipas, trabalhadores, turnos, produção, causas de RNC e formações.</p></div>`;$("exportBtn").onclick=downloadJson;$("importFile").onchange=importJson}
function downloadJson(){const blob=new Blob([JSON.stringify(exportDb(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="RNC_Impressao_v3.json";a.click();URL.revokeObjectURL(a.href)}
function importJson(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{importDb(JSON.parse(r.result));db=loadDb();alert("Dados importados.");render()}catch(err){alert("Ficheiro inválido.")}};r.readAsText(file)}
function renderAi(){$("ai").innerHTML=`<div class="card"><h2>IA</h2><p>Espaço reservado para importar fotografia de relatórios e preencher dados automaticamente.</p><p class="small">Fluxo previsto: carregar foto → IA lê OF/RNC/máquina/equipa/turno/causas → utilizador confirma → app grava no JSON.</p></div>`}

document.addEventListener("DOMContentLoaded",init)
