let db=loadDb();
let currentView="dashboard";
let pendingProfile=null;
const SHIFTS=["Manhã","Tarde","Noite"];

const VIEW_LABELS={dashboard:"Dashboard",production:"Produção",structure:"Estrutura",profiles:"Fichas",stats:"Estatística",data:"Dados",ai:"Assistente IA"};

function $(id){return document.getElementById(id)}
function init(){document.querySelectorAll(".drawer-nav button").forEach(b=>b.onclick=()=>{show(b.dataset.view);closeMenu()});$("menuBtn").onclick=openMenu;$("closeDrawer").onclick=closeMenu;$("overlay").onclick=closeMenu;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMenu()});initTheme();show("dashboard")}
function openMenu(){$("drawer").classList.add("open");$("overlay").classList.add("show");$("drawer").setAttribute("aria-hidden","false")}
function closeMenu(){$("drawer").classList.remove("open");$("overlay").classList.remove("show");$("drawer").setAttribute("aria-hidden","true")}
function initTheme(){applyTheme(localStorage.getItem("omp_theme")||"light");$("themeToggle").onclick=()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark")}
function applyTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem("omp_theme",t);$("themeToggle").textContent=t==="dark"?"☀️ Mudar para modo claro":"🌙 Mudar para modo escuro"}
function show(view){currentView=view;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(view).classList.add("active");document.querySelectorAll(".drawer-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const tv=$("topbarView");if(tv)tv.textContent=VIEW_LABELS[view]||view;render()}
function render(){db=loadDb();if(currentView==="dashboard")renderDashboard();if(currentView==="production")renderProduction();if(currentView==="structure")renderStructure();if(currentView==="profiles")renderProfiles();if(currentView==="stats")renderStats();if(currentView==="data")renderData();if(currentView==="ai")renderAi()}

function kpis(records){const a=aggregate(records);return `<div class="grid"><div class="kpi click-card" onclick="show('production')">OF<b>${a.of}</b></div><div class="kpi click-card" onclick="show('production')">RNC<b>${a.rnc}</b></div><div class="kpi">Taxa RNC/100 OF<b>${fmt(a.taxa)}</b></div><div class="kpi">OF por RNC<b>${a.ofRnc?String(a.ofRnc.toFixed(1)).replace(".",","):"Sem RNC"}</b></div></div>`}
function bar(label,value,max,suffix=""){const w=max?Math.max(3,value/max*100):3;return `<div class="barline"><div class="barlabel">${label}</div><div class="barbox"><div class="bar" style="width:${w}%">${String(value.toFixed?value.toFixed(2):value).replace(".",",")}${suffix}</div></div></div>`}
function selectOptions(list,value="",empty=""){return (empty?`<option value="">${empty}</option>`:"")+list.map(x=>`<option value="${x.id}" ${x.id===value?"selected":""}>${x.name}</option>`).join("")}
function shiftOptions(value="",empty="Escolher"){return (empty?`<option value="">${empty}</option>`:"")+SHIFTS.map(s=>`<option value="${s}" ${s===value?"selected":""}>${s}</option>`).join("")}
function machineOptions(sectionId="",value=""){return selectOptions(db.machines.filter(m=>!sectionId||m.sectionId===sectionId),value,"Escolher")}
function workerChecks(selected=[]){return db.workers.map(w=>`<label><input type="checkbox" value="${w.id}" ${selected.includes(w.id)?"checked":""}> ${workerLabel(w)} <span class="small">(${w.shift||"turno não definido"})</span></label>`).join("")||"<p class='small'>Sem trabalhadores criados.</p>"}
function teamOptionsForMachine(machineId){return selectOptions(db.teams.filter(t=>!machineId||!t.machineId||t.machineId===machineId),"","Sem equipa")}
function recordShift(r){if(r.shift)return r.shift;const t=db.teams.find(x=>x.id===r.teamId);return t?.shift||"Não definido"}
function goProfile(type,id){pendingProfile={type,id};show("profiles")}

function sectionTotals(records){return db.sections.map(s=>{const recs=records.filter(r=>r.sectionId===s.id);const a=aggregate(recs);return{section:s,...a}})}
function pieChart(title,metric,records){const totals=sectionTotals(records);const flex=totals.find(x=>x.section.id==="flexo")||{of:0,rnc:0};const roto=totals.find(x=>x.section.id==="roto")||{of:0,rnc:0};const flexValue=metric==="rnc"?flex.rnc:flex.of;const rotoValue=metric==="rnc"?roto.rnc:roto.of;const total=flexValue+rotoValue;const deg=total?flexValue/total*360:0;const winner=metric==="of"?(flexValue>rotoValue?"Flexografia":rotoValue>flexValue?"Rotogravura":"Empate"):"";return `<div class="card"><h2>${title}</h2><div class="pie-wrap"><div class="pie" style="--deg:${deg}deg" title="Flexografia ${flexValue} / Rotogravura ${rotoValue}"></div><div class="legend"><div class="legend-item clickable" onclick="goProfile('section','flexo')"><span class="dot flexo"></span>Flexografia: ${flexValue}</div><div class="legend-item clickable" onclick="goProfile('section','roto')"><span class="dot roto"></span>Rotogravura: ${rotoValue}</div><div>Total: <b>${total}</b></div>${metric==="of"?`<div class="winner">Vencedor em OF: ${winner}</div>`:""}</div></div></div>`}
function topMachines(records,field,limit=3,desc=true){return db.machines.map(m=>({machine:m,a:aggregate(records.filter(r=>r.machineId===m.id))})).filter(x=>field==="of"?x.a.of>0:x.a.rnc>0).sort((a,b)=>desc?((field==="of"?b.a.of:b.a.rnc)-(field==="of"?a.a.of:a.a.rnc)):((field==="of"?a.a.of:a.a.rnc)-(field==="of"?b.a.of:b.a.rnc))).slice(0,limit)}
function machineRankingCard(title,items,field){const max=Math.max(...items.map(x=>field==="of"?x.a.of:x.a.rnc),1);return `<div class="card"><h2>${title}</h2>${items.length?items.map(x=>{const value=field==="of"?x.a.of:x.a.rnc;return `<div class="barline"><div class="barlabel machine-link" onclick="goProfile('machine','${x.machine.id}')">${x.machine.name}</div><div class="barbox"><div class="bar" style="width:${Math.max(3,value/max*100)}%">${value}</div></div><div class="small">${fmt(x.a.taxa)}</div></div>`}).join(""):"<p class='small'>Sem dados.</p>"}</div>`}
function alerts(records){const avg=aggregate(records).taxa||0;const byMachine=db.machines.map(m=>({m,agg:aggregate(records.filter(r=>r.machineId===m.id))})).filter(x=>x.agg.of>0).sort((a,b)=>(b.agg.taxa||0)-(a.agg.taxa||0));if(!byMachine.length)return"<p class='small'>Sem dados.</p>";return `<p>Pior máquina por taxa: <span class="machine-link" onclick="goProfile('machine','${byMachine[0].m.id}')">${byMachine[0].m.name}</span> (${fmt(byMachine[0].agg.taxa)}).</p><p>Média global: <b>${fmt(avg)}</b>.</p>`}

function renderProduction(){const years=db.productionRecords.map(r=>r.year);const year=years.length?Math.max(...years):new Date().getFullYear();$("production").innerHTML=`<div class="card"><h2>Produção mensal</h2><div class="grid"><div><label>Ano</label><input id="pYear" type="number" value="${year}"></div><div><label>Mês</label><select id="pMonth">${MONTHS.map((m,i)=>`<option value="${i}">${m}</option>`).join("")}</select></div><div><label>Secção</label><select id="pSection">${selectOptions(db.sections,"","Escolher")}</select></div><div><label>Máquina</label><select id="pMachine"></select></div><div><label>Equipa</label><select id="pTeam"></select></div><div><label>Turno</label><select id="pShift">${shiftOptions()}</select></div><div><label>OF/trabalhos</label><input id="pJobs" type="number" min="0"></div><div><label>RNC</label><input id="pRnc" type="number" min="0"></div><div><label>Causa principal</label><input id="pCause" placeholder="Ex: limpeza, setup, tinta"></div></div><label>Trabalhadores presentes</label><div id="pWorkers">${workerChecks([])}</div><label>Observações</label><textarea id="pNotes"></textarea><button class="btn" id="addRecord">Guardar registo</button></div><div class="card"><h2>Últimos registos</h2><div id="recordList"></div></div>`;$("pSection").onchange=()=>{$("pMachine").innerHTML=machineOptions($("pSection").value);$("pMachine").dispatchEvent(new Event("change"))};$("pMachine").onchange=()=>{$("pTeam").innerHTML=teamOptionsForMachine($("pMachine").value)};$("pTeam").onchange=()=>{const t=db.teams.find(x=>x.id===$("pTeam").value);if(t?.shift)$("pShift").value=t.shift};$("pSection").dispatchEvent(new Event("change"));$("addRecord").onclick=addRecord;renderRecordList()}
function addRecord(){const workerIds=[...document.querySelectorAll("#pWorkers input:checked")].map(x=>x.value);const rec={id:uid("rec"),year:n($("pYear").value),month:n($("pMonth").value),sectionId:$("pSection").value,machineId:$("pMachine").value,teamId:$("pTeam").value,shift:$("pShift").value,workerIds,jobs:n($("pJobs").value),rnc:n($("pRnc").value),cause:$("pCause").value.trim(),notes:$("pNotes").value.trim()};if(!rec.sectionId||!rec.machineId)return alert("Escolhe secção e máquina.");db.productionRecords.push(rec);saveDb(db);renderProduction()}
function renderRecordList(){const rows=[...db.productionRecords].slice(-12).reverse();$("recordList").innerHTML=rows.length?`<table><tr><th>Data</th><th>Secção</th><th>Máquina</th><th>Equipa</th><th>Turno</th><th>OF</th><th>RNC</th><th>Taxa</th></tr>${rows.map(r=>`<tr><td>${MONTHS[r.month]} ${r.year}</td><td class="clickable" onclick="goProfile('section','${r.sectionId}')">${sectionName(db,r.sectionId)}</td><td class="machine-link" onclick="goProfile('machine','${r.machineId}')">${machineName(db,r.machineId)}</td><td>${teamName(db,r.teamId)}</td><td>${recordShift(r)}</td><td>${r.jobs}</td><td>${r.rnc}</td><td>${fmt(rate(r.rnc,r.jobs))}</td></tr>`).join("")}</table>`:"<p class='small'>Sem registos.</p>"}

function renderStructure(){$("structure").innerHTML=`<div class="row"><div class="card"><h2>Máquinas</h2><div class="grid"><input id="mName" placeholder="Ex: IF5"><select id="mSection">${selectOptions(db.sections)}</select><input id="mMaker" placeholder="Fabricante"><input id="mYear" placeholder="Ano"></div><button class="btn" id="addMachine">Adicionar máquina</button><div id="machineTable"></div></div><div class="card"><h2>Equipas</h2><input id="tName" placeholder="Nome (opcional, gerado automaticamente)"><select id="tMachine">${selectOptions(db.machines,"","Escolher máquina")}</select><select id="tShift">${shiftOptions()}</select><p class="small" id="tSuggested"></p><button class="btn" id="addTeam">Adicionar equipa</button><div id="teamTable"></div></div></div><div class="card"><h2>Trabalhadores</h2><div class="grid"><input id="wName" placeholder="Nome"><input id="wNumber" placeholder="Nº mecanográfico"><input id="wNationality" placeholder="Nacionalidade"><input id="wBirth" type="date"><input id="wCompanyYears" type="number" placeholder="Anos na empresa"><input id="wPrintYears" type="number" placeholder="Anos na impressão"><select id="wTeam">${selectOptions(db.teams,"","Sem equipa")}</select><select id="wShift">${shiftOptions()}</select><input id="wRole" placeholder="Função"></div><label>Notas / formação / competências</label><textarea id="wNotes"></textarea><button class="btn" id="addWorker">Adicionar trabalhador</button><div id="workerTable"></div></div>`;$("addMachine").onclick=addMachine;$("tMachine").onchange=()=>{$("tSuggested").textContent=$("tMachine").value?`Nome sugerido: ${teamAutoName(db,$("tMachine").value)}`:""};$("addTeam").onclick=addTeam;$("addWorker").onclick=addWorker;renderStructureTables()}

function createMachine({name,sectionId,manufacturer,year}){if(!name)return null;const m={id:name,name,sectionId,manufacturer,year,status:"active",statusNote:"",notes:""};db.machines.push(m);saveDb(db);return m}
function createTeam({name,machineId,shift}){if(!machineId)return null;const machine=db.machines.find(x=>x.id===machineId);const finalName=(name&&name.trim())||teamAutoName(db,machineId);const t={id:uid("team"),name:finalName,sectionId:machine.sectionId,machineId,shift,members:[]};db.teams.push(t);saveDb(db);return t}
function createWorker({name,number,nationality,birthDate,yearsCompany,yearsPrinting,teamId,shift,role,notes}){if(!name)return null;const w={id:uid("worker"),name,number,nationality,birthDate,yearsCompany:n(yearsCompany),yearsPrinting:n(yearsPrinting),teamId,shift,role,notes};db.workers.push(w);saveDb(db);return w}
function upsertRncQuick({machineId,year,month,jobs,rnc}){if(!machineId)return null;const machine=db.machines.find(x=>x.id===machineId);const existing=db.productionRecords.find(r=>r.machineId===machineId&&r.year===year&&r.month===month);if(existing){existing.jobs=jobs;existing.rnc=rnc}else{db.productionRecords.push({id:uid("rec"),year,month,sectionId:machine.sectionId,machineId,teamId:"",shift:"",workerIds:[],jobs,rnc,cause:"",notes:"Registo rápido"})}saveDb(db);return{created:!existing}}

function addMachine(){const name=$("mName").value.trim();if(!name)return;createMachine({name,sectionId:$("mSection").value,manufacturer:$("mMaker").value,year:$("mYear").value});renderStructure()}
function addTeam(){const machineId=$("tMachine").value;if(!machineId)return alert("Escolhe uma máquina.");createTeam({name:$("tName").value.trim(),machineId,shift:$("tShift").value});renderStructure()}
function addWorker(){const name=$("wName").value.trim();if(!name)return;createWorker({name,number:$("wNumber").value.trim(),nationality:$("wNationality").value.trim(),birthDate:$("wBirth").value,yearsCompany:$("wCompanyYears").value,yearsPrinting:$("wPrintYears").value,teamId:$("wTeam").value,shift:$("wShift").value,role:$("wRole").value.trim(),notes:$("wNotes").value.trim()});renderStructure()}
function renderStructureTables(){ $("machineTable").innerHTML=`<table><tr><th>Máquina</th><th>Secção</th><th>Fabricante</th><th>Ano</th></tr>${db.machines.map(m=>`<tr><td class="machine-link" onclick="goProfile('machine','${m.id}')">${m.name}</td><td class="clickable" onclick="goProfile('section','${m.sectionId}')">${sectionName(db,m.sectionId)}</td><td>${m.manufacturer||"—"}</td><td>${m.year||"—"}</td></tr>`).join("")}</table>`;$("teamTable").innerHTML=`<table><tr><th>Equipa</th><th>Máquina</th><th>Turno</th><th>Membros</th></tr>${db.teams.map(t=>{const members=db.workers.filter(w=>w.teamId===t.id).map(workerLabel).join(", ")||"—";return `<tr><td class="clickable" onclick="goProfile('team','${t.id}')">${t.name}</td><td>${t.machineId?machineName(db,t.machineId):"—"}</td><td>${t.shift||"—"}</td><td class="left small">${members}</td></tr>`}).join("")}</table>`;$("workerTable").innerHTML=`<table><tr><th>Nome</th><th>Nacionalidade</th><th>Equipa</th><th>Turno</th><th>Exp. impressão</th></tr>${db.workers.map(w=>`<tr><td class="clickable" onclick="goProfile('worker','${w.id}')">${workerLabel(w)}</td><td>${w.nationality||"—"}</td><td>${teamName(db,w.teamId)}</td><td>${w.shift||"—"}</td><td>${w.yearsPrinting||0}</td></tr>`).join("")}</table>`}

function renderProfiles(){const opts=`<option value="">Escolher</option>`;$("profiles").innerHTML=`<div class="card"><h2>Fichas</h2><div class="grid"><div><label>Secção</label><select id="fSection">${opts+db.sections.map(s=>`<option value="${s.id}">${s.name}</option>`).join("")}</select></div><div><label>Máquina</label><select id="fMachine">${opts+db.machines.map(m=>`<option value="${m.id}">${m.name}</option>`).join("")}</select></div><div><label>Equipa</label><select id="fTeam">${opts+db.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join("")}</select></div><div><label>Trabalhador</label><select id="fWorker">${opts+db.workers.map(w=>`<option value="${w.id}">${workerLabel(w)}</option>`).join("")}</select></div></div></div><div id="profileOut"></div>`;["fSection","fMachine","fTeam","fWorker"].forEach(id=>$(id).onchange=()=>{pendingProfile=null;renderProfileOut()});if(pendingProfile){const map={section:"fSection",machine:"fMachine",team:"fTeam",worker:"fWorker"};const el=$(map[pendingProfile.type]);if(el)el.value=pendingProfile.id;}renderProfileOut()}
function profile(title,sub,records,extra=""){return `<div class="card profile-card"><h2>${title}</h2><p class="small">${sub}</p>${kpis(records)}${extra}</div>`}
function renderProfileOut(){let html="";const s=$("fSection")?.value,m=$("fMachine")?.value,t=$("fTeam")?.value,w=$("fWorker")?.value;if(s)html+=profile("Ficha da secção — "+sectionName(db,s),"Dados agregados da secção.",recordsFor(db,{sectionId:s}));if(m){const machine=db.machines.find(x=>x.id===m);html+=profile("Ficha da máquina — "+machineName(db,m),`Secção: ${sectionName(db,machine.sectionId)}. Fabricante: ${machine.manufacturer||"—"}. Ano: ${machine.year||"—"}.`,recordsFor(db,{machineId:m}))}if(t){const team=db.teams.find(x=>x.id===t);const members=db.workers.filter(x=>x.teamId===t).map(workerLabel).join(", ")||"Sem membros atribuídos.";html+=profile("Ficha da equipa — "+teamName(db,t),`Máquina: ${team?.machineId?machineName(db,team.machineId):"—"}. Turno: ${team?.shift||"—"}.`,recordsFor(db,{teamId:t}),`<p><b>Membros:</b> ${members}</p>`)}if(w){const worker=db.workers.find(x=>x.id===w);const age=worker.birthDate?Math.floor((Date.now()-new Date(worker.birthDate))/(365.25*24*3600*1000)):"—";html+=profile("Ficha do trabalhador — "+workerLabel(worker),`Idade: ${age}. Nacionalidade: ${worker.nationality||"—"}. Equipa: ${teamName(db,worker.teamId)}. Turno: ${worker.shift||"—"}.`,recordsFor(db,{workerId:w}),`<p><b>Experiência:</b> ${worker.yearsCompany||0} anos na empresa, ${worker.yearsPrinting||0} anos na impressão.</p><p><b>Função:</b> ${worker.role||"—"}</p><p><b>Notas:</b> ${worker.notes||"—"}</p><p class="small">Dados de desempenho são associados aos registos onde o trabalhador esteve presente. Usar para análise estatística, não culpabilização.</p>`)}$("profileOut").innerHTML=html||"<div class='card'><p class='small'>Escolhe uma entidade para abrir a ficha.</p></div>"}

function renderStats(){const all=recordsFor(db,{});const byTeam=db.teams.map(t=>({name:t.name,a:aggregate(recordsFor(db,{teamId:t.id}))})).filter(x=>x.a.of>0);const max=Math.max(...byTeam.map(x=>x.a.of),1);$("stats").innerHTML=`<div class="card"><h2>Estatística</h2>${kpis(all)}</div><div class="card"><h2>Ranking de equipas por OF</h2>${byTeam.map(x=>bar(x.name,x.a.of,max)).join("")||"<p class='small'>Sem dados por equipa.</p>"}</div><div class="card"><h2>Influência por turno</h2>${shiftStats()}</div><div class="card"><h2>Estatísticas de trabalhadores</h2>${workerStats()}</div>`}
function shiftStats(){const rows=SHIFTS.concat(["Não definido"]).map(shift=>{const recs=db.productionRecords.filter(r=>recordShift(r)===shift);return{shift,a:aggregate(recs)}}).filter(x=>x.a.of>0);if(!rows.length)return"<p class='small'>Sem dados por turno.</p>";return `<table><tr><th>Turno</th><th>OF</th><th>RNC</th><th>Taxa</th><th>OF/RNC</th></tr>${rows.map(x=>`<tr><td>${x.shift}</td><td>${x.a.of}</td><td>${x.a.rnc}</td><td>${fmt(x.a.taxa)}</td><td>${x.a.ofRnc?x.a.ofRnc.toFixed(1).replace(".",","):"Sem RNC"}</td></tr>`).join("")}</table>`}
function workerStats(){if(!db.workers.length)return"<p class='small'>Sem trabalhadores.</p>";const avgExp=db.workers.reduce((a,w)=>a+n(w.yearsPrinting),0)/db.workers.length;const nat={};db.workers.forEach(w=>nat[w.nationality||"Não indicado"]=(nat[w.nationality||"Não indicado"]||0)+1);return `<p>Experiência média em impressão: <b>${avgExp.toFixed(1).replace(".",",")} anos</b></p><table><tr><th>Nacionalidade</th><th>Nº trabalhadores</th></tr>${Object.entries(nat).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join("")}</table>`}

function downloadJson(){const blob=new Blob([JSON.stringify(exportDb(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="RNC_Impressao_v3.json";a.click();URL.revokeObjectURL(a.href)}
function importJson(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{importDb(JSON.parse(r.result));db=loadDb();alert("Dados importados.");render()}catch(err){alert("Ficheiro inválido.")}};r.readAsText(file)}
function renderAi(){$("ai").innerHTML=`<div class="card"><h2>Assistente IA</h2><p class="small">Responde apenas com base nos dados registados na app — nunca inventa valores. Tolera erros de escrita.</p><div id="chatLog" class="chat-log"></div><div id="chatChips" class="chips"></div><div class="chat-input"><input id="chatInput" placeholder="Ex: qual a pior máquina?" autocomplete="off"><button class="btn" id="chatSend">Enviar</button></div></div><div class="card"><h2>Importação por fotografia</h2><p class="small">Funcionalidade futura: carregar foto de relatório → a IA lê OF, RNC, máquinas, equipas, turnos e causas → confirmas → os dados entram no JSON.</p></div>`;initChat()}

document.addEventListener("DOMContentLoaded",init)
